(lang dune 3.1)

(name alvie)

(version 2026.09)

(generate_opam_files true)

(authors "Matteo Busi, Riccardo Focardi, Flaminia Luccio")
(maintainers "Matteo Busi, Riccardo Focardi, Flaminia Luccio")

(license LICENSE)

(package
 (name alvie)
 (synopsis "ALVIE/VaultLink: learn and check Mealy models of the VaultLink network service")
 (description "")
 (depends
  (ocaml (>= "4.13"))
  alcotest
  core
  core_unix
  fmt
  logs
  ocamlgraph
  ppx_deriving
  ppx_hash
  ppx_jane
  ppx_sexp_conv)
 (tags
  ("automata learning" "formal verification" "alvie" "vaultlink")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
