#!/bin/bash

if [[ "$OSTYPE" == darwin* ]]; then
    shopt -s expand_aliases
    alias sed='gsed'
fi

###############################################################################
#                            Arguments, fixed                                  #
###############################################################################
tmpdir="$1"
basename="$2"
# With --no-mem the IHEX -> MEMH conversion is left to the caller
mode="$3"

scriptsdir=../scripts
srcdir=../src

asmfile=$tmpdir/$basename.s43


incfilev="$tmpdir/sancus-core-gap/core/rtl/verilog/openMSP430_defines.v";
incfile=$tmpdir/pmem.h

linkfile="$tmpdir/sancus-core-gap/core/sim/rtl_sim/bin/template.x";
# linkfile=$scriptsdir/template.x;
headfile="$tmpdir/sancus-core-gap/core/sim/rtl_sim/bin/template_defs.asm"
#headfile=$scriptsdir/template_defs.asm;
sancus_macro="sancus_macros.asm"


# If on MacOS, used gsed
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias sed="gsed"
fi

# Everything but the program itself is the same for every build in $tmpdir:
# prepare it only once (the marker is written last, after a successful setup)
setup_marker=$tmpdir/.build_pmem_setup_done

cp $asmfile $tmpdir/pmem.s43

if [ ! -f "$setup_marker" ]; then
# Copy necessary files
cp $srcdir/$sancus_macro $tmpdir/$sancus_macro
cp $scriptsdir/omsp_config.sh $tmpdir/omsp_config.sh

cp $incfilev  $incfile
sed -ie 's/`ifdef/#ifdef/g'   $incfile
sed -ie 's/`ifndef/#ifndef/g' $incfile
sed -ie 's/`else/#else/g'     $incfile
sed -ie 's/`endif/#endif/g'   $incfile
sed -ie 's/`define/#define/g' $incfile
sed -iee 's/`include/\/\/#include/g' $incfile
sed -ie 's/`//g'              $incfile
sed -ie "s/'//g"              $incfile

# Use MSPGCC preprocessor to extract the Program, Data
# and Peripheral memory sizes
if command -v msp430-gcc >/dev/null; then
    msp430-gcc -E -P -x c $tmpdir/omsp_config.sh > $tmpdir/pmem.sh
else
    msp430-elf-gcc -E -P -x c $tmpdir/omsp_config.sh > $tmpdir/pmem.sh
fi
fi

# Source the extracted configuration file
source $tmpdir/pmem.sh

# Compile assembler code
echo "Compile, link & generate IHEX file (Program Memory: $pmemsize B, Data Memory: $dmemsize B, Peripheral Space: $persize B)..."
if [ -f "$setup_marker" ]; then
    export ASM2IHEX_SKIP_DEFS=1
fi
$scriptsdir/asm2ihex.sh $tmpdir/pmem $tmpdir/pmem.s43 $linkfile $headfile $pmemsize $dmemsize $persize "$tmpdir" || exit 1
touch "$setup_marker"

if [ "$mode" == "--no-mem" ]; then
    exit 0
fi

# # Generate Program memory file
echo "Convert IHEX file to Verilog MEMH format..."
$scriptsdir/ihex2mem.tcl -ihex $tmpdir/pmem.ihex -out $tmpdir/$basename.mem -mem_size $pmemsize
